from typing import Protocol

from ..model import Device, LightState, SoundEffect


class Driver(Protocol):
    async def discover(self) -> list[Device]: ...
    async def snapshot(self, identifier: str, device: Device) -> dict: ...
    async def apply(self, identifier: str, device: Device, state: LightState) -> None: ...
    async def restore(self, identifier: str, device: Device, snapshot: dict) -> None: ...
    async def identify(self, identifier: str, device: Device) -> None: ...
    async def play(self, identifier: str, device: Device, effect: SoundEffect) -> None: ...
